/* Generated by Together */
#include "stdafx.h"
#ifndef USE_IOCP

#include "GameServerApp.h"
#include <iostream>
#include <time.h>
#include "GameCommon.h"
#include "SubMap.h"
#include "GameApp.h"
#include "TryUtil.h"

_DBC_USING
// Network buffer size table; do not modify order!
uLong	NetBuffer[]		={100,10,0};
bool	g_logautobak	=true;
//End

extern BOOL	g_bGameEnd; // GameServer shutdown flag


// Thread: periodically reconnect dropped GateServer connections
long ConnectGateServer::Process()
{T_B
    DWORD	dwTick, dwCurTick;
    DWORD	dwInterval = 5000;
    DWORD	dwConnectTick = 0;

    dwTick = dwCurTick = GetTickCount();
    dwTick -= dwConnectTick; // Offset so first connection attempt happens immediately

    while (!GetExitFlag())
        {
        dwCurTick = GetTickCount();

        static DWORD dwLastRunTick = 0;
        if(dwCurTick - dwLastRunTick < dwInterval) 
            {
            Sleep(10);
            continue;}

        dwLastRunTick = dwCurTick;

        // Attempt to reconnect any disconnected GateServers
        if (dwCurTick - dwTick >= dwConnectTick)
            {
            dwTick = dwCurTick;
            for (int i = 0; i < m_gmsvr->m_gtnum; i++)
                if (!m_gmsvr->m_gtarray[i].IsValid())
                    m_gmsvr->ConnectGate(&m_gmsvr->m_gtarray[i]);
            }
        }

    return 0;
T_E}

// Thread: connect / keep-alive with InfoServer
long ToInfoServer::Process()
{T_B
	if(m_gmsvr->m_IfServer.GetPort() == 0)
	{
		//LG("Store_data", "InfoServer not configured!\n");
		LG("Store_data", "not configure InfoServer!\n");
		return 0;
	}

	m_gmsvr->m_IfServer.InValid();
	LG("Store_data", "Connect InfoServer(%s, %d)...\n", m_gmsvr->m_IfServer.GetIP().c_str(), m_gmsvr->m_IfServer.GetPort());
	g_gmsvr->ConnectInfo(&m_gmsvr->m_IfServer);

	DWORD	dwCurTick;
	DWORD	dwInterval = m_dwTimeOut;

	dwCurTick = GetTickCount();

	// InfoServer login loop
	while(!GetExitFlag())
	{
		dwCurTick = GetTickCount();

		static DWORD dwLastRunTick = 0;
		if(dwCurTick - dwLastRunTick < dwInterval) 
		{
			Sleep(10);
			continue;
		}

		try
		{
			if(!m_gmsvr->m_IfServer.IsValid() && m_gmsvr->m_IfServer.IsConnect())
			{
				LG("Store_data", "Login InfoServer...\n");
				m_gmsvr->m_IfServer.Login();
			}
		}
		catch(...)
		{
			LG("Store_data", "Process Error!\n");
		}

		dwLastRunTick = dwCurTick;
	}

	LG("Store_data", "ToInfoServer Process Out!\n");

	return 0;
T_E}

void InfoServer::Login()
{T_B
	pNetMessage pNm = new NetMessage();
	char szPwd[33];
	cChar *szPassword = (cChar *)GetPassword();

    // Add by lark.li 20090311 begin
    if (!szPassword)
        return;
    // End

	if(strlen(szPassword) > 32)
	{
		LG("Store_data", "Login password too long!\n");
		return;
	}
	strcpy(szPwd, szPassword);
	BuildNetMessage(pNm, INFO_LOGIN, 0, 0, 0, (unsigned char*)szPwd, long(strlen(szPwd) + 1));
	g_gmsvr->GetInfoServer()->SendData(pNm);
	FreeNetMessage(pNm);
T_E}

long InfoServer::PeekMsg(unsigned long ms)
{T_B
    // Clamp minimum wait to 10 ms
    if(ms < 10)
        ms = 10;

    while(ms-- > 0)
    {
        if(!m_MsgQueue.IsEmpty())
        {
            pNetMessage msg = m_MsgQueue.Pop();
            g_gmsvr->ProcessData(msg, CMD_FM_MSG);
        }
        else
            break;
    }
	return 0;
T_E}

void InfoServer::OnConnect(bool result)
{
	if(result)
	{
		LG("Store_data", "InfoServer Connected!\n");
		g_gmsvr->ProcessData(NULL, CMD_FM_CONNECTED);
	}
	else
	{
		LG("Store_data", "InfoServer Connect Failed!\n");

		try
		{
			//g_gmsvr->DisconnectInfo(this);
		}
		catch(...)
		{
			LG("Store_data", "OnConnect Error!\n");
		}
		
	}
}

void InfoServer::OnDisconnect()
{
    InValid();
	LG("Store_data", "InfoServer Disconnected!\n");

	try
	{
		//g_gmsvr->DisconnectInfo(this);
	}
	catch(...)
	{
		LG("Store_data", "OnDisconnect Error!\n");
	}
	
    g_gmsvr->ProcessData(NULL, CMD_FM_DISCONNECTED);
}

// Constructor: set up network, gates, InfoServer
GameServerApp::GameServerApp(ThreadPool *proc,ThreadPool *comm)
    :TcpClientApp(this,proc,comm), RPCMGR(this), m_count(0), PKQueue(false)
{T_B
	//LG("init", "Starting ServerApp init\n");	
	LG("init", "start init ServerApp\n");	

	// Seed random number generator
	srand( (unsigned)time( NULL ) );

    // Read this GameServer's name from config
    m_strGameName = g_Config.m_szName;

    // Initialize GateServer connection info from config
    m_gtnum = min(MAX_GATE, g_Config.m_nGateCnt);
    for (int i = 0; i < m_gtnum; ++ i)
        {
        m_gtarray[i].GetIP() = g_Config.m_szGateIP[i];
        m_gtarray[i].GetPort() = g_Config.m_nGatePort[i];
        m_gtarray[i].m_playerlist = NULL;}

    // Configure InfoServer connection
    m_IfServer.SetInfoServer(g_Config.m_szInfoIP, g_Config.m_nInfoPort, g_Config.m_szInfoPwd, g_Config.m_nSection);

    // Set packet parser params and start network layer
    SetPKParse(0,2,32*1024,400);
    BeginWork(g_Config.m_lSocketAlive);

	//LG("init", "ServerApp init complete\n");
	LG("init", "ServerApp init over\n");
T_E}

GameServerApp::~GameServerApp()
{T_B
	if(m_IfServer.IsConnect())
	{
		DisconnectInfo(&m_IfServer);
		LG("Store_data", "Disconnect InfoServer!\n");
	}

	ShutDown(2*1000);
T_E}

// Return true to accept, false to reject the incoming connection
bool GameServerApp::OnConnect(DataSocket *datasock)
{T_B
    datasock->SetRecvBuf(64*1024); 
    datasock->SetSendBuf(64*1024);

    LG("Connect", "GateServer Connected! IP = [%s] port = %d\n",  datasock->GetPeerIP() , datasock->GetPeerPort());
   return true;
T_E}

// reason: 0 = normal disconnect, -3 = protocol error, -1 = socket error, -5 = peer shutdown.
void GameServerApp::OnDisconnect(DataSocket *datasock,int reason)
{T_B
    LG("Connect", "GateServer Disconnect! IP = [%s] port = %d, reason = [%s]\n",  datasock->GetPeerIP() , datasock->GetPeerPort(), GetDisconnectErrText(reason).c_str());

    GateServer* gt = (GateServer *)datasock->GetPointer();
    if (gt == NULL) return;


    //TODO(Ogge): Check how this actually work:
    // GateServer::IsValid() will return true until the packet CMD_MM_GATE_RELEASE has been processed
    // Could this function be called n-times and in turn send this packet n-times before its actually invalidated
    if (!gt->IsValid()) return;
    m_mutdisconn.lock();
    do {
        // dual-check
        if (!gt->IsValid()) break;

        // Queue a Gate-release packet so game thread cleans up players
        WPacket pkt = GetWPacket();
        pkt.WriteCmd(CMD_MM_GATE_RELEASE);
		pkt.WriteLongLong(ToAddress(gt->m_playerlist));
        auto rpkt = RPacket(pkt);
        AddPK(datasock, rpkt);

        // Invalidate GateServer
        //gt->Invalid(); // Handled later in CGameApp::OnGateDisconnect callback

    } while (false);
    m_mutdisconn.unlock();

T_E}

void GameServerApp::OnProcessData(DataSocket *datasock,RPacket &pk)
{T_B
    AddPK(datasock, pk);
T_E}

void GameServerApp::ProcessData(DataSocket* datasock, RPacket& pk)
{T_B
    if (datasock == NULL) return;
    GateServer* gt = (GateServer *)datasock->GetPointer();
    if (gt == NULL) return;

    int msg_id;
    uShort cmd = pk.ReadCmd();
    switch (cmd)
        {
        case CMD_MM_GATE_CONNECT:
		    LG("Connect", "ProcessData Gate_Connect\n");
            msg_id = NETMSG_GATE_CONNECTED;
            break;

        case CMD_MM_GATE_RELEASE:
            msg_id = NETMSG_GATE_DISCONNECT;
            break;

        default:
            msg_id = NETMSG_PACKET;
            break;
        }

    g_pGameApp->ProcessNetMsg(msg_id, gt, pk);
T_E}

void GameServerApp::ProcessData(pNetMessage msg, short sType)
{T_B
    switch (sType)
    {
    case InfoServer::CMD_FM_CONNECTED:
        break;

    case InfoServer::CMD_FM_DISCONNECTED:
        break;

    case InfoServer::CMD_FM_MSG:
        break;

    default:
        break;
    }

    g_pGameApp->ProcessInfoMsg(msg, sType, GetInfoServer());
T_E}

WPacket	GameServerApp::OnServeCall(DataSocket *datasock, RPacket &pk)
{T_B
	uShort l_cmd = pk.ReadCmd();
	switch (l_cmd)
	{
		case CMD_TM_KICKCHA: return TM_KICKCHA(datasock, pk);
		case CMD_TM_OFFLINE_MODE: return TM_OFFLINE_MODE(datasock, pk);
	}
	return 0;
T_E}

WPacket	GameServerApp::TM_KICKCHA(DataSocket *datasock, RPacket &pkt)
{
	WPacket	l_retpk = GetWPacket();

	///NOTE(Ogge): Lets lock this to prevent possible data race?
	auto const m = std::lock_guard{m_mutdisconn};
	long lChaDbID = READ_LONG(pkt);
	CPlayer* pCOldPly = g_pGameApp->FindPlayerByDBChaID(lChaDbID);
	if (!pCOldPly || !pCOldPly->IsValid())
	{
		l_retpk.WriteChar(0);
	}
	else
	{
		pCOldPly->GetCtrlCha()->BreakAction();
		pCOldPly->MisLogout();
		pCOldPly->MisGooutMap();
		g_pGameApp->ReleaseGamePlayer(pCOldPly);
		l_retpk.WriteChar(1);
	}
	return l_retpk;
}

dbc::WPacket GameServerApp::TM_OFFLINE_MODE(dbc::DataSocket* datasock, RPacket& rpk)
{
	auto player = ToPointer<CPlayer>((rpk.ReverseReadLongLong()));
	CCharacter* pCCha{};

    auto wpk = GetWPacket();
	const auto return_code = [&]
	{
        if (!player)
        {
            return ReturnCode::OfflineMode::Unknown;
        }

        if (player->GetGateAddr() != rpk.ReverseReadLongLong())
        {
            return ReturnCode::OfflineMode::Unknown;
        }

		if (!player->IsValid())
		{
			return ReturnCode::OfflineMode::Unknown;
		}

		if (player->GetMainCha()->GetPlayer() != player)
		{
			return ReturnCode::OfflineMode::Unknown;
		}

		if (!g_Config.m_bOfflineMode)
		{
			return  ReturnCode::OfflineMode::Disabled;
		}

		
		if (pCCha = player->GetCtrlCha(); !pCCha)
		{
			return ReturnCode::OfflineMode::Unknown;
		}
        
        if (!pCCha->IsLiveing())
        {
			return ReturnCode::OfflineMode::Dead;
        }

		if (auto map = pCCha->GetSubMap();
			map && !map->CanSavePos())
		{
			return ReturnCode::OfflineMode::Refuse;
		}

        if (pCCha->IsBoat())
        {
			return ReturnCode::OfflineMode::Refuse;
        }


		return  ReturnCode::OfflineMode::Success;
	}();

	if (return_code != ReturnCode::OfflineMode::Success)
    {
		// Stalling wasn't allowed for some reason, return early
		wpk.WriteChar(static_cast<uint8_t>(return_code));
		return wpk;
    }

	constexpr auto hour_in_ms = 60 * 60 * 1000;
    pCCha->_dwStallTick = GetTickCount() + (g_Config.m_dwStallTime * hour_in_ms);
	g_pGameApp->CanReceiveRequests(player->GetID(), false); //NOTE(Ogge): Why isn't this called inside CPlayer::SetCanRecieveRequests()?
	player->SetCanReceiveRequests(false);
	wpk.WriteChar(static_cast<uint8_t>(return_code));

	return wpk;
}

// Connect to a GateServer
void GameServerApp::ConnectGate(GateServer* pGate)
{T_B
    if (pGate->IsValid()) return;

    DataSocket* datasock = Connect(pGate->GetIP().c_str(), pGate->GetPort());
    if (datasock == NULL)
    {
		//LG("Connect", "Failed to connect GateServer, ip = %s, port = %d.\n", pGate->GetIP().c_str(), pGate->GetPort() ); 
		LG("Connect", "connect to  GateServer failed, ip = %s, port = %d.\n", pGate->GetIP().c_str(), pGate->GetPort() ); 
	}
    else 
	{
        pGate->SetDataSock(datasock);
        datasock->SetPointer(pGate);
		// Announce this GameServer to the newly connected GateServer
		WPacket wpkt = GetWPacket();
		wpkt.WriteCmd(CMD_MM_GATE_CONNECT);
		wpkt.WriteChar(0);
        auto rpkt = RPacket(wpkt);
		AddPK(datasock, rpkt);
	}
T_E}

// Connect to InfoServer
bool GameServerApp::ConnectInfo(InfoServer *pInfo)
{T_B
	//pInfo->StopInfoService();
    pInfo->RunInfoService(pInfo->GetIP().c_str(), pInfo->GetPort());
	return true;
T_E}

void GameServerApp::DisconnectInfo(InfoServer *pInfo)
{T_B
    pInfo->StopInfoService();
T_E}

bool GameServerApp::IsValidGate(int i)
{T_B
    if (i < 0 || i > m_gtnum) throw std::logic_error("gate index out of range!");

    return m_gtarray[i].IsValid();
T_E}

GateServer* GameServerApp::FindGate(char const* gt_name)
{T_B
    for (int i = 0; i < m_gtnum; ++ i)
    {
        if (m_gtarray[i].IsValid())
        {
            if (m_gtarray[i].GetName().compare(gt_name) == 0)
                return &m_gtarray[i];
        }
    }

    return NULL;
T_E}


// Player linked list management
bool GameServerApp::AddPlayer(GatePlayer* gtplayer, GateServer* gt, LONG64 gtaddr)
{T_B
    if (gt == NULL || gtplayer == NULL) return false;
    if (!gt->IsValid()) return false;
	if (gtplayer->Next || gtplayer->Prev)
	{
		//LG("character list error", "insert character dbid %u failed: link pointers are not empty!\n", gtplayer->GetDBChaId());
		LG("character list error ", "insert character dbid %u failed: link pointers not empty!\n", gtplayer->GetDBChaId());
		return false;
	}

    // Assign gate reference to this GatePlayer
    gtplayer->SetGate(gt);
    gtplayer->SetGateAddr(gtaddr);

    // Link gtplayer at the head of the list
    gtplayer->Prev = NULL;
    gtplayer->Next = gt->m_playerlist;

    if (gtplayer->Next != NULL)
        gtplayer->Next->Prev = gtplayer;

    // Update list head
    gt->m_playerlist = gtplayer;

	gt->AddPlayerCount();    
    return true;
T_E}

bool GameServerApp::DelPlayer(GatePlayer* gtplayer)
{T_B
    if (gtplayer == NULL) return false;

    GateServer* gt = gtplayer->GetGate();
    if (gt == NULL || !gt->IsValid()) return false;

	if (gt->m_listcurplayer == gtplayer)
		gt->m_listcurplayer = gtplayer->Next;
    // Remove gtplayer from doubly-linked list
    if ((gtplayer->Prev == NULL) && (gtplayer->Next == NULL))
        {
        if (gtplayer == gt->m_playerlist)
            { // Only element in the list
				gt->m_playerlist = NULL;
            }
        else { // Stale / already-removed gtplayer
            return false;}
        }
    else if ((gtplayer->Prev == NULL) && (gtplayer->Next != NULL))
        { // Head node
			if (gtplayer != gt->m_playerlist) return false;

			gt->m_playerlist = gtplayer->Next;
			gt->m_playerlist->Prev = NULL;

        gtplayer->Next = NULL;
        }    
    else if ((gtplayer->Prev != NULL) && (gtplayer->Next == NULL))
        { // Tail node
        gtplayer->Prev->Next = NULL;

        gtplayer->Prev = NULL;
        }
    else { // Middle node
        gtplayer->Prev->Next = gtplayer->Next;
        gtplayer->Next->Prev = gtplayer->Prev;

        gtplayer->Prev = NULL;
        gtplayer->Next = NULL;
        }

	gt->DecPlayerCount();
	return true;
T_E}

bool GameServerApp::KickPlayer(GatePlayer* gtplayer, long lTimeSec)
{T_B
    //WPacket pkt = GetWPacket();
    //pkt.WriteCmd(CMD_MT_KICKUSER);
	//pkt.WriteLong(lTimeSec);
    //return SendToClient(pkt, gtplayer);
	return KickPlayer2(gtplayer);
T_E}

bool GameServerApp::KickPlayer2(GatePlayer *gtplayer)
{T_B
	WPacket pkt = GETWPACKET();
	pkt.WriteCmd(CMD_MT_KICKUSER);
	pkt.WriteLong(gtplayer->GetDBChaId());
	pkt.WriteLongLong(gtplayer->GetGateAddr());
	pkt.WriteShort(1);
	gtplayer->GetGate()->SendData(pkt);
	return true;
T_E}

bool GameServerApp::SendToGroup(WPacket& chginf)
{
    GateServer* pGate;

    // Route through the first valid Gate
    for (int i = 0; i < m_gtnum; ++ i)
        {
        pGate = &m_gtarray[i];

        if (pGate->IsValid())
        {
			chginf.WriteShort( 0 );
			pGate->SendData(chginf);
			return true;
        }
	}
    return true;
}

// Broadcast to all players on all Gates
bool GameServerApp::SendToWorld(WPacket& chginf)
{T_B
    WPacket		CChginf;
    Short		sCount;

    GatePlayer* pPlayer;
    GateServer* pGate;

    // Duplicate packet per Gate and append each Gate's player addresses
    for (int i = 0; i < m_gtnum; ++ i)
        {
        pGate = &m_gtarray[i];

        if (pGate->IsValid())
            {
            sCount = 0;
            CChginf = chginf.Duplicate();

			pPlayer = pGate->m_playerlist;
            while (pPlayer != NULL)
                {
                CChginf.WriteLong(pPlayer->GetDBChaId());
                CChginf.WriteLongLong(pPlayer->GetGateAddr());
                sCount++;

                pPlayer = pPlayer->Next;}

            if (sCount > 0)
                {
                CChginf.WriteShort(sCount);
                pGate->SendData(CChginf);}
            }
        }

    return true;
T_E}

bool GameServerApp::SendToClient(GatePlayer* player, WPacket& pkt)
{T_B
    if (player == NULL) return false;

    GateServer* pGate = player->GetGate();
    if (pGate != NULL)
    {
        pGate->SendData(pkt);
        return true;
    }
    else
    {
        return false;
    }
T_E}

bool GameServerApp::SendToClient(WPacket& pkt, GatePlayer* playerlist)
{T_B
    if (playerlist == NULL) return false;

    // Prepare per-Gate packet duplicates
    uShort		usCount[MAX_GATE];
    WPacket		CChginf[MAX_GATE];
    GateServer* pValidGate[MAX_GATE];
    Short		sValidGateNum = 0;    
    for (int i = 0; i < m_gtnum; ++ i)
        {
        if (m_gtarray[i].IsValid())
            {
            pValidGate[sValidGateNum] = &m_gtarray[i];
            usCount[sValidGateNum] = 0;
            CChginf[sValidGateNum] = pkt.Duplicate();
            sValidGateNum++;
            }
        }

    // Walk playerlist and append each player's address to its Gate's packet
    GatePlayer* tmp = playerlist;
    while (tmp != NULL)
    {
        if (tmp->GetGate() == NULL)
        {      
#ifdef defCOMMU_LOG
            LG("SendToClient", "WARNING! pGate = NULL, atorID=%d, gt_addr=0x%x\n",
                tmp->GetDBChaId(), tmp->GetGateAddr());
#endif
        }
        else
        {
            for (int i = 0; i < sValidGateNum; ++ i)
            {
                if (tmp->GetGate() == pValidGate[i])
                {
                    usCount[i]++;
                    CChginf[i].WriteLong(tmp->GetDBChaId());
                    CChginf[i].WriteLongLong(tmp->GetGateAddr());
                    break;
                }
            }
        }

        tmp = tmp->GetNextPlayer();
    }

    // Finalize and send each Gate's packet (write player count trailer)
    for (int i = 0; i < sValidGateNum; i++)
        {
        if (usCount[i] > 0)
            {
            CChginf[i].WriteShort(usCount[i]);
            pValidGate[i]->SendData(CChginf[i]);
            }
        }

    return true;
T_E}

bool GameServerApp::SendToClient(WPacket& pkt, int array_cnt, uplayer* uplayer_array)
{T_B
    if (uplayer_array == NULL) return false;

#ifdef defCOMMU_LOG
    //LG("SendToClient", "\nSendToClient called to notify %d players\n", array_cnt);
#endif

    // Prepare per-Gate packet duplicates
    uShort		usCount[MAX_GATE];
    WPacket		CChginf[MAX_GATE];
    GateServer* pValidGate[MAX_GATE];
    Short		sValidGateNum = 0;    
    for (int i = 0; i < m_gtnum; ++ i)
    {
        if (m_gtarray[i].IsValid())
        {
            pValidGate[sValidGateNum] = &m_gtarray[i];
#ifdef defCOMMU_LOG
            //LG("SendToClient", "Valid Gate 0x%x\n", pValidGate[sValidGateNum]);
#endif
            usCount[sValidGateNum] = 0;
            CChginf[sValidGateNum] = pkt.Duplicate();
            sValidGateNum++;
        }
    }
#ifdef defCOMMU_LOG
    //LG("SendToClient", "Valid Gate num = %d\n", sValidGateNum);
#endif

    // Walk uplayer_array and append each player's address to its Gate's packet
    int j;
    for (int i = 0; i < array_cnt; ++ i)
    {
#ifdef defCOMMU_LOG
        //LG("SendToClient", "atorID = %d, pGate = 0x%x, gt_addr = 0x%x\n", uplayer_array[i].m_dwDBChaId, uplayer_array[i].pGate, uplayer_array[i].m_ulGateAddr);
#endif

        if (uplayer_array[i].pGate == NULL)
        {
#ifdef defCOMMU_LOG
            LG("SendToClient", "WARNING! pGate = NULL, atorID=%d, gt_addr=0x%x\n",
                uplayer_array[i].m_dwDBChaId, uplayer_array[i].m_ulGateAddr);
#endif
            continue;
        }

        for (j = 0; j < sValidGateNum; ++ j)
        {
            if (uplayer_array[i].pGate == pValidGate[j])
            {
                usCount[j]++;
                CChginf[j].WriteLong(uplayer_array[i].m_dwDBChaId);
                CChginf[j].WriteLongLong(uplayer_array[i].m_ulGateAddr);
                break;
            }
        }
    }

    // Finalize and send each Gate's packet (write player count trailer)
    for (int i = 0; i < sValidGateNum; i++)
    {
#ifdef defCOMMU_LOG
        //LG("SendToClient", "send to Gate: %s for %d players\n", pValidGate[i]->GetIP().c_str(), usCount[i]);
#endif
        if (usCount[i] > 0)
        {            
            CChginf[i].WriteShort(usCount[i]);
            pValidGate[i]->SendData(CChginf[i]);
        }
    }

    return true;
T_E}

bool GameServerApp::SendToGame(WPacket& pkt, uplayer* uplyr)
{T_B
    return (uplyr->pGate->SendData(pkt) > 0) ? true : false;
T_E}



GameServerApp* g_gmsvr;

#endif
